version: '3'
services:
  nodejs-app:
    image: node:14
    container_name: nodejs-app
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: production
    command: npm start
    expose:
      - 3000

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nodejs-app

networks:
  default:
    external:
      name: nginx-proxy
