version: '3'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    expose:
      - 3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: dds_line
      MYSQL_PASSWORD: rvbu*KRtAZXV
      MYSQL_DATABASE: doe-dds
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nodejs-app
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: r9weXRfhad4D@
      MYSQL_DATABASE: test_mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql-files:/var/lib/mysql-files
#Volumes
volumes:
  dbdata:
    driver: local
networks:
  default:
    external:
      name: nginx-proxy
